name = "nuxtsupabase"
type = "javascript"
account_id = "fc08588692d3f34a216a433e6d49611f"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-04-07"

[site]
bucket = ".output/public"
entry-point = ".output"

[build]
command = ""
upload.format = "service-worker"

[miniflare]
https = true